### ISSUE TITLE
Related project

### ISSUE THREAD

**Issue by dandv** [senthilp/snap#1]
Hey Senthil,

Greetings from Google :) I was checking out your GitHub and found this project, while coincidentally I was also working on a newer version of a very similar library - https://github.com/dandv/imagecapture/

**Comment by senthilp** [comment]
Hey @dandv I did this project a long time back. Nice to see that you are working on a newer version.  The [demo](https://github.com/dandv/imagecapture#demo) link in your project should be updated to https://dandv.github.io/imagecapture/ Will play around and give you feedback.

**Comment by dandv** [comment]
Good catch, thanks! I've fixed the link.
